### ISSUE TITLE
After updating a private message it disappears from the recipients matrix

### ISSUE THREAD

**Issue by cvogeley** [friendica/red#102]
Tested on my server friendicared.de.
1. Create a private post with ACL-rights just for another channel (which I own).
-->Post is visible on the matrix of the other channel. An @-tag is created for the target channel (Should that be the case?)
2. Make an update and save
---> Another @-tag for the channel is created
--> post disappears from matrix of the other channel. But permission still work when you access the profile where the post was made.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#37
