### ISSUE TITLE
save to folder doesn't work outside network page

### ISSUE THREAD

**Issue by friendica** [friendica/red#113]
Via mrjive:

@Mike Macgirvin a small bug: if I click on "SAVE IN A FOLDER" (sorry if the desccription is not correct, I'm translating from interface which is in italian and I couldn't find quickly wher to change it) it works only if I am in the "NETWORK" while it doesn't if I see the post via the "LINK TO ORIGINAL"

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#42
