### ISSUE TITLE
clicking tag reveals private posts

### ISSUE THREAD

**Issue by tazmandevil** [friendica/red#114]
When I click on a tag link, while not authenticated to any hub, I find posts I had made with that tag, even though the permissions for my channel are "only those I specifically allow" for "who can see my posts".
This seems contrary to the permissions concept.
I've been able to reproduce it numerous times now.
I log out of all hubs, go to https://red.tazmandevil.info/channel/blog/ and click any tag link in the tag cloud, and, BOOM, I see posts from tazman@red.tazmandevil.info (my channel with very private settings).
I'm not particularly concerned with the posts I found, but I'm certain there are folks who would consider this a serious issue.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#43
