### ISSUE TITLE
Accept connection to allow communication in orange frame for visibility

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#131]
When receiving an introduction it is necessary to check the box next to

"Accept connection to allow communication"

and hit the Save-button to make the connection work. However, the checkbox and label is drowned out and does not stand out on this page.

I will suggest to put it in a coloured frame - orange - to make it instantly visible.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#48
