### ISSUE TITLE
fix include paths

### ISSUE THREAD

**Issue by dsp1986** [friendica/red#140]
Yesterday I installed red on my server. To get through the installation I needed to fix 3 paths:
("include" was missing)

mod/setup.php:289 require_once('include/datetime.php') 
index.php:53 require_once("include/session.php") 
index.php:105 require_once('include/auth.php')

---

this is the first time I'm using github. I managed to change the files on my server and upload the commit to my fork (dsp1986/red). Should I do a pull request?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#50
