### ISSUE TITLE
APW theme - jumps up into previous comments - prevents further comment reading

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#145]
This is probably a browser issue. I use Firefox Aurora, 25.0a2 (2013-09-16). If a post has enough comments, trying to read the expanded thread to the end is impossible, and the browser jumps up into the previously read comments, preventing reading the thread to the end. Seems to be around the fifth comment in a thread.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#52
