### ISSUE TITLE
Make search box find posts if the search string matches a channel

### ISSUE THREAD

**Issue by zzottel** [friendica/red#159]
Two possible solutions:

1) Say a channel is named "foo bar" and its address is http://foo.org/channel/fbr. If the search string is foo, bar, "foo bar", or fbr, also return all posts and comments from that channel.

2) (Probably better in my opinion.) Provide a dropdown menu in the search box similar to those presented in browsers to choose the search engine in the search box. Make it possible to search in posts or to search posts by channels that match the search string.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#110
