### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by GutHib** [friendica/red#167]
I would like to help debug this script, but can't even get it installed. I uploaded the contents of red-master.zip to the server, but when I access the site, all I get is: "Apologies but this site is unavailable at the moment. Please try again later."

Any pointers?

Thanks. :)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#56

**Comment by hybotics** [comment]
I have the same issue, but this is not in include/config.php. It is in include/dba.php and dba_pdo.php. It's in this code segment in both files:

        if(! $this->connected) {
            $this->db = null;
            if(! $install)
                system_unavailable();
        }
