### ISSUE TITLE
template designs

### ISSUE THREAD

**Issue by TsGenesis** [friendica/red#186]
I can not find a template that really works for mainstream general audience. I found a couple, but I think it would be cool to make a template look and move like an ipad / iphone app that is completely responsive.
![templateidea](https://f.cloud.github.com/assets/5806027/1432408/19afbd3e-40de-11e3-9174-70e208f53a7b.png)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#60
