### ISSUE TITLE
Show if and maybe when posts/comments were edited

### ISSUE THREAD

**Issue by zzottel** [friendica/red#189]
Classic case: Someone posts "Kittens are cute" and gets a lot of likes and comments, and later changes the post to "Adolf Hitler was the greatest politician ever".

Dumb example, but much more sophisticated alterations of this might actually cause real problems for users if the edited state of a post/comment isn't shown.

This should be a theme feature, as it is not or not always desirable for blogs and web pages, but should be present in Redbasic so that all themes copying it will have that feature by default.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#61
