### ISSUE TITLE
xchan_photo fields changing on new profile photo upload

### ISSUE THREAD

**Issue by Gadget-Guru** [friendica/red#225]
After primary hub change; I tried changing my profile photo by uploading a new one and now the xchan_photo fields keep changing themselves for example from https://sethmartin.us/photo/profile/l/1 to https://sethmartin.us/photo/5d1d298e69ee0dffde3951c763665a8f-4

I have tried changing them back, but not only am I the only one that can view my new photo, if I edit my profile using a different clone, it goes back to the https://sethmartin.us/photo/5d1d298e69ee0dffde3951c763665a8f-4 that I don't want.

The profile photo change was a fresh upload on the new primary hub.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#65
