### ISSUE TITLE
Photos from connection not showing in matrix stream.

### ISSUE THREAD

**Issue by Gadget-Guru** [friendica/red#226]
Some connections can view the photos in their matrix stream, but some cannot.

Magic-Auth Diagnostic returns:
Local Setup returns: Array
(
[success] => 1
[url] => https://redmtx.com/post/?f=&auth=seth%40sethmartin.us&sec=f08f25468ea664e6f01863caec092bfa6aa303d1f99050bab4a02069edb495da&dest=https%3A%2F%2Fredmtx.com%2Fphoto%2F8a158fd395da35ad63a51d881b79ec79-2.jpg&version=1
[message] => token f08f25468ea664e6f01863caec092bfa6aa303d1f99050bab4a02069edb495da created for channel 1 for url https://redmtx.com

)
Remote site responded:

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#66
