### ISSUE TITLE
Post deletion not working on complex delivery chains

### ISSUE THREAD

**Issue by zzottel** [friendica/red#230]
I just sent a test post to my whisky channel (group/forum style permissions) with ACL set to that channel as only recipient, the channel being @-mentioned, to test if the post was delivered to a test channel of mine on beardyunixer.com which is connected to whisky, but not to my main channel. That delivery worked.

Then I deleted that test post.

It was deleted from the wall of the whisky channel, but it was not deleted from the network/ page of my test channel at beardyunixer.com, i.e. it seems that the deletion message wasn't forwarded to the forum members of the whisky channel.

I don't have any logs of this, but if required I can create some with another test, of course.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#67
