### ISSUE TITLE
Specifying photo size when posting wall photo while uploading causes prohibition sign.

### ISSUE THREAD

**Issue by Gadget-Guru** [friendica/red#237]
Specifying photo size when posting wall photo while uploading causes prohibition sign, due to poster's channel hash being left under allow_cid in the photo table making it viewable for poster only.

For example:
Changing the default

```
[zrl=https://libertypod.com/photos/test/image/954430c4a7af8f342b6313520dc0654b][zmg]https://libertypod.com/photo/954430c4a7af8f342b6313520dc0654b-2.jpg[/zmg][/zrl]
```

to

```
[zrl=https://libertypod.com/photos/test/image/954430c4a7af8f342b6313520dc0654b][zmg]https://libertypod.com/photo/954430c4a7af8f342b6313520dc0654b.jpg[/zmg][/zrl]
```

will cause channel hash being left under allow_cid.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#68
