### ISSUE TITLE
Umlauts in categories not delivered to others correctly

### ISSUE THREAD

**Issue by zzottel** [friendica/red#240]
In a post on https://red.zottel.net/channel/zottelszeug I used the category "Elektromobilität heute". It is correctly shown on that channel, but on my main channel (connected to zottelszeug), I see "Elektromobilit auml;t heute" (plus &, but can't write that here without gettig an ä again), i.e. HTML-encoded.

Looking into the term table, I see the correct entry with utf8-chars in zottelszeug and the incorrect one with auml for zottel there.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#69
