### ISSUE TITLE
Uncollapsed Show More collapses again on every reload on display/ pages

### ISSUE THREAD

**Issue by zzottel** [friendica/red#256]
Title says it all. Very unpleasant especially for blogs if a certain long article is linked to from elsewhere.

At least for blogs, it would be ideal if Show More wasn't used at all (at least for the top-level post) on display pages, and I think that would make sense for non-blog uses, too.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#113
