### ISSUE TITLE
display/ pages don't use the theme of the channel

### ISSUE THREAD

**Issue by zzottel** [friendica/red#257]
If I look at a display/ page of my blog unathenticated, it is not displayed with the blog channel's theme, but with the server's default theme.

This is the case if I visit the display/ page directly as linked from somewhere else.

If I look at my blog first (unauthenticated again), then go to a display/ page from there, the blog theme is used, but not with the channel's settings, i.e. in my case ( https://red.zottel.net/channel/zottelszeug ), I suddenly get a completely different APW look.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#70
