### ISSUE TITLE
include/gprobe.php kicking my server's arse

### ISSUE THREAD

**Issue by tonybaldwin** [friendica/red#317]
I rebooted my server (intended to reboot desktop, but forgot I was logged into the server on that terminal, doh). and when it came back up for over an hour it was spinning like mad, so I logged back in and did htop and found a handful of processes of
/usr/bin/php include/gprobe.php 
were chewing up CPU cycles like your mom chews chips.
I killed them, and it hasn't come back...yet.
The only thing I could find in logs at all was in red/log/php.log
this:
01:26:19 UTC] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/red/include/Contact.php on line 117

tony

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#114
