### ISSUE TITLE
Strings in library/jquery.divgrow don't get translated

### ISSUE THREAD

**Issue by solstag** [friendica/red#336]
Ni!

Pages that use jquery.divgrow will display the strings "+ Show More" and "- Show Less" without translating them.

Apparently we're only using it in "views/js/main.js" on line 538.

Jquery.divgrow lets you specify those strings as arguments like this:

.divgrow({ initialHeight: 400, moreText: "show more text", lessText: "show less text", showBrackets: false })

But we're currently not using that, and I have no idea how to place translated string inside javascript.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#74
