### ISSUE TITLE
notification dropdown menu broken

### ISSUE THREAD

**Issue by ghost** [friendica/red#351]
Overnight notification dropdown menus from "Your Matrix" etc have broken.

Using  Iceweasel from Debian, Redbasic theme.

I get the numbers appearing as normal and then where I would expect to get the list forming the menu, I get a horizontal list saying undefined repeatedly.

this is needed at the bottom of nav.tpl for notifications to work:
https://red.pixelbits.de/display/2b53e9b8e3daef0605591a57213aa95deb156d7f36c22bd3d4c56245e09e340a@red.mariovavti.com

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#77
