### ISSUE TITLE
wrong url for zot-info in webfinger

### ISSUE THREAD

**Issue by fabrixxm** [friendica/red#360]
`/.well-known/webfinger?resource=acct:user@host` returns

```
[...]
{
  "href": "http://host/.well-known/zot-info?zaddr=useri@host", 
  "rel": "http://purl.org/zot/protocol"
}
[...]
```

but correct url is

```
/.well-known/zot-info?address=user@host
```

btw: is Red getting "zot-info" url from webfinger or is hardcoded to be `/.well-known/zot-info` ?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#78
