### ISSUE TITLE
Incorrect font colour in dark scheme of the redbasic theme

### ISSUE THREAD

**Issue by ghost** [friendica/red#364]
Drop down menus, text fields (but not all) and more elements have a light font on a light background. The text becomes unreadable. The text only becomes readable when selecting the text with the mouse. 

I think this can resolved in two different ways:
1. Making the font colour of those elements dark, because these elements have a light background.
2. Make the background of these elements dark, but that actually means that similar elements that are displayed correctly,  needs to be changed to.

I think 1 is the fastest solution.

![light-onlight](https://f.cloud.github.com/assets/3049892/2387694/cd8ca948-a939-11e3-924e-f8065f1b2754.png)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#79
