### ISSUE TITLE
Global crosspost/share plugin

### ISSUE THREAD

**Issue by ghost** [friendica/red#368]
This is a feature request.

Currently people must write a complete plugin if they want to crosspost/share to another website (like Libertree). Is it not a good idea to simplify this with one common plugin that accepts API's from external sites? I think this will make the whole sharing to external sites part of Red Matrix a lot more stable and streamlined. It will also be a lot easier to maintain and external sites can easier be added.

Let me explain by an simple image I just made (site names are examples): 

![redmatrix](https://f.cloud.github.com/assets/3049892/2461583/5e8ad624-af78-11e3-8e42-6b9e67e90d60.png)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#81
