### ISSUE TITLE
Duplicate term in two tags in same post cause problems for second tag

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#378]
I made a post with #Drammen and #Drammen_City_Hall_from_1871 and saved. In both tags, only "Drammen" was high-lighted, the bit from " _City_Hall_from_1871" was not. I changed the last tag to "City_Hall_from_1871", and worked. The problem seems to be with the same term twice, here "Drammen", even though these are different tags in the same post.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#87
