### ISSUE TITLE
Race condition in connected forum-like channels

### ISSUE THREAD

**Issue by ghost** [friendica/red#383]
There is a race condition causing a loop when two taggable channels are mentioned from the same post, if the two channels have permissions to receive each other's posts and tags (typically with "anyone on the internet" settings for both, but also if the two channels are connected to each other).

Bob tags Alice and Carol.

Alice receives the post, and sends a copy to Bob and Carol.

Carol receives the post, and sends it to Alice and Bob.

Alice sends the post straight back to Carol who immediately returns it to Alice, etc

This doesn't go on forever (though can happen hundreds of times), so it must be a race condition rather than a loop, however I just can't see what conditions stop it.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#89
