### ISSUE TITLE
Changing profile photo not working

### ISSUE THREAD

**Issue by GutHib** [friendica/red#388]
Hi,

I am having problems changing my profile photo (to a point where I am pretty sure it's a bug ;). What I do is I click in the left-hand upper corner with the colorful default avatar, upon which I get a bigger colorful default avatar. Now I can check the small pen icon, click on "change profile photo", then on the photo on the right I would like to use, and finally on "Use as profile photo". Then I see a smaller default avatar, and the avatar in the left-hand upper corner is unchanged as well. Now I click on that left-hand upper avatar again and [insert infinite loop].

Tried to log out and in again - no change. Hopefully you can reproduce this.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#91

**Comment by RogerSik** [comment]
Hello,

 i have this problem and additionally problem with newewst version (v. 3.4) also.

I explan it so:

User 1 has a new profil piiture (1 week old image)
User 2 has a new profil picture (1 week old image)
User 3 has a profil picture (2 week old image)

On the home site of User 1 i see on the friends site the friendica default picture from User 2 and the right profil picture User 3, but User 1 has his new profil picutere.

On the home site of User 2 the User 1 has his old profil picture.

On the home site of User 3 the User 1 has his new profil picture.

[User 1] (https://friendica.sikorski.cc/profile/roger)
[User 2] (https://friendica.sikorski.cc/profile/fp)
[User 3] (https://friendica.sikorski.cc/profile/it-blog)

Sometimes I'm see the new profil picture with the same browser.

**Comment by jeroenpraat** [comment]
This repository is closed. Also the issue. See https://github.com/redmatrix/redmatrix/issues/91
