### ISSUE TITLE
Is the javascript free?

### ISSUE THREAD

**Issue by ghost** [friendica/red#389]
I am using LibreJS because of this https://www.gnu.org/philosophy/javascript-trap.html

And LibreJS told me redmatrix is using nonfree javascript, as defined here https://www.gnu.org/software/librejs/free-your-javascript.html

Sometimes LibreJS mistakenly thinks a page has nonfree js, so just want to ask, and possibly suggest following the "free your javascript" guide. :-)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#93
