### ISSUE TITLE
suggestion to clarify Default Post Location

### ISSUE THREAD

**Issue by ghost** [friendica/red#392]
I searched documentation, DDG and Google but was unable to find the meaning of Default Post Location, and experimentation did not reveal its function either. Perhaps a context-bubble could be added for when the cursor hovers over the heading.

![screenshot from 2014-04-02 20 03 47](https://cloud.githubusercontent.com/assets/5033268/2598795/de85534c-bacf-11e3-9946-652398c0c8ac.png)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#94
