### ISSUE TITLE
Professional-looking Skin

### ISSUE THREAD

**Issue by GutHib** [friendica/red#394]
Hi,

I think it's fantastic what you've guys have achieved so far with the RedMatrix. There's only one issue - to be able to make full use of the script, I would have to convince my friends to join and they are geeky below average.

To be honest, RedMatrix still doesn't LOOK all that appealing at this point, which is what I see as a huge stumbling block. So I wanted to ask if there's a professional/flashy/cool design already in the works, or if there's at least a cookie jar that is designated for this exact purpose? I am very sure that getting the design right would go a VERY long way, even if the odd feature might still be missing at this point.

Thanks!

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#117
