### ISSUE TITLE
UI work

### ISSUE THREAD

**Issue by friendica** [friendica/red#395]
Per Alexandre Hannud Abdo:

Dear @Channel One

Some usability issues we should fix soon, with suggested fixes.

This is feedback from two workshops for over 30 people I held this week, everyone of which registered on my server, created a channel, added each other and exchanged messages. So I'm not not just coming up with a lot of blablabla.

0) The default privacy settings, both the channel and connection settings, should correspond to one of the simple privacy options we give, specifically those labeled as typical. There should also be visual feedback when one selects one of those options, like making it bold and perhaps adding a check mark. The advanced privacy settings button, in fact anything advanced, should not be that much more visible than the rest of the content.

1) Chanview either shouldn't be default, or should have a link on that first column to open the channel as its own page. Also, when looking at an already connected channel it should say "Connected" and provide a link to edit the connection.

2) Pages accessible through channel tabs, like File and Chatrooms, should always display the channel tabs themselves.

3) Clicking on someone's name should always yield the same page, regardless of whether the name is in a comment author header, in a mention, or in a like.

4) Clicking on someone's name, regardless of their privacy settings, should always take you to a page with a link to connect to them, or if already connected, with a link to edit that connection.

5) When browsing an individual image or file, the page should display bbcode for easy copy/paste to properly include it in a message or comment. Would be nice to have that to link to albums as well.

6) The conections link in the navbar (the humanoid figure) should only take you to the new connections page if there are new connections, otherwise it should show all connections.

7) On the connections page, the avatar icons should be links to view the channel, with a separate link to edit the connection.

That's all for now =)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#118
