### ISSUE TITLE
Profile-photos in gallery circumvents the privacy of photos used in non-public photos

### ISSUE THREAD

**Issue by jkrenzer** [friendica/red#410]
Hi! 
A little privacy-leak to savor as your sunday lunch. ;-)

Tested against: git d0834c7

Setting:
- Channel Alice creates (standard) public profile A and hidden profile B.
- Channel Alice adds a obscured photo as public avatar to A and a photo showing her real face to B.

Behavior of red:
- Anybody with permission to view gallery of Alice can go to the gallery and see the public as well as the all private avatar-photo in "profile photos".

Expected behavior:
- Profile pictures should not leak between profiles.

Suggested fix:
- Hide all profile-photos for everyone except the owner. 

Are you with me on this one?

Kind regards

Jörn

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#100
