### ISSUE TITLE
A general UI solution to connect to a channel upon visiting it

### ISSUE THREAD

**Issue by solstag** [friendica/red#413]
This comes from issue #395 in item number 3, after Mike explained why chanview is not portable enough to make the distributed privacy model usable in a large and very private setting. (pardon my french)

We need a better solution to the question of "how do I figure out how to connect - and thus request permissions - to this channel that threw a blank page with a 'no permissions' floating thing in my face?"

My current thought goes in the direction of using the navbar for that.

What if the navbar on a remote channel, beyond information on the channel that is visiting, also displayed information on the channel being visited?

When the visitor is authenticated, it could provide a menu to handle the interaction between the two channels, with links to connect, edit connection, and later perhaps even source, clone and other things you can do from one channel to another.

Is there a technical reason why the navbar would not be suitable for this?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#101
