### ISSUE TITLE
Clone-synchronizing of profile-information and -pictures not working.

### ISSUE THREAD

**Issue by jmankiewicz** [friendica/red#419]
As the title says:

When I change my profile or add a new one the changes don't get synced to the other hosts of my channel. Sychronisation of messages and connections work flawlessly. 

Tested with current HEAD on multiple instances. As I'm not knee-deep into Zot and red's synchronisation, I would be gratefully for any hint were to start hunting for debug-information. 

Regards

Jörn

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#120
