### ISSUE TITLE
Congratulations!!! - > 10.000 commits

### ISSUE THREAD

**Issue by abinoam** [friendica/red#420]
Hey guys,

I've been "off" for a while. But I love Friendica/Red people and the project.
Even being a little "off" I always take a look on the progress.
And today I was suprised to the >10.000 commits on the red codebase!
I just would like to say CONGRATULATION!!! 
Apart from any code metric flame war, 10.000 commits in any metric is really a great milestone.

I have just looked on "another" project that had 200.000 bucks to speed things up and they have 14.000! 10.000 commits for Red without having almost any financial help, is really amazing. 

Congratulations to you all. Specially for Mike McGirvin ( @friendica ), Tobias ( @tobiasd ), Fabio (@fabrixxm) and  Thomas (@beardy-unixer ).

PS: Raising this as a github issue to keep the record of this milestone on github itself.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#102
