### ISSUE TITLE
Can not register at own hub

### ISSUE THREAD

**Issue by einervonvielen** [friendica/red#421]
Task
A user wants to register at a Red Matrix hub, version 2014-04-18.650R+170b5d9

Steps:
1. open http://einervonvielen.mooo.com/login (example)
2. Press "Register"

Expected
- A new user can register at http://einervonvielen.mooo.com/

Observed
- http://einervonvielen.mooo.com/pubsites
- A new user can only register at public hubs.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#188
