### ISSUE TITLE
Show position on map via OSM not working

### ISSUE THREAD

**Issue by einervonvielen** [friendica/red#426]
Steps:
- Setting > Channel Settings > Use Browser Location: = checked
- Share something
- Klick on the link "Map" (next to my avatar)
- The browser opens http://nominatim.openstreetmap.org/?lat=54.3443447&lon=13.5030036&zoom=17

Expected
- An OSM map (zoom 17) is shown with marker for the location

Observed
- An OSM map of the world is shown but WITHOUT marker for the location

Proposed solution
- Use https://www.openstreetmap.org/#map=17/54.34434/13.50300

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#191
