### ISSUE TITLE
Webpages - permissions - user selection lost - permission denied

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#432]
I have created a page I want to discuss with two other channel users, and I click the Show button on each of these users, then the Close button or the X in the upper right corner.

One of the channel users is one of my own channels, so I changed to that channel and tried to view the page, but got access denied.

Going back to my channel which owns the webpage and opening the permission settings for the page again, the user selections are lost - only I have permission.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#193
