### ISSUE TITLE
When clicking on one notification item, mark whole thread as seen

### ISSUE THREAD

**Issue by ghost** [friendica/red#433]
I don't know if this was removed by accident or on purpose, but I like to request an old feature.

In the past when you clicked on a notification item (in the dropdown menu) the whole thread was marked as seen. Now when you click on an item only that specific comment is marked as seen. The only way to mark all threads as seen is to use the 'mark all notifications as seen' link. 
I think it is more user friendly to have the old behaviour back. Because when you click on one comment notification, you also go to the other comments.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#194
