### ISSUE TITLE
Notification system skipping mentions when multiple mentions present

### ISSUE THREAD

**Issue by solstag** [friendica/red#459]
Ni!

I can faithfully reproduce the following with latest git and also have users telling me this has been going on for a while:

Usar A mentions user C => User C gets an email notification.

Usar A mentions user D => User D gets an email notification.

Usar A mentions users C and D in the same message => User C gets an email notification but user D does not.

The order in which the mentions appear in the message does not seem to matter.

I have also seen this:

User A mentions users C, D and E in individual messages => They get emailed.

User A mentions users C, D and E in the same message => Users C and D get emailed but user E does not.

Something seems to be wrong with the logic of handling whom to notify and email, I'm looking at the code but haven't figured it out yet...

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#203
