### ISSUE TITLE
Links that are posted to libertree doesn't look too good

### ISSUE THREAD

**Issue by annando** [friendica/red#461]
When a post goes to libertree, links aren't formatted nicely. Libertree needs another way of treating links.

At the moment it looks like this:
```
#[1](http://www.forbes.com/sites/craigsilver/2014/05/15/funnyball-baseball-statistics-wed-like-to-see/ "") 
```
The libertree parser shows it this way. The title of the link is at the end of the post which doesn't look nice.

In Friendica this works. AFAIK we changed something in the markdownify class.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#121
