### ISSUE TITLE
translation depends on browser

### ISSUE THREAD

**Issue by xavierle** [friendica/red#465]
actually i have a quite strange issue. which is not so urgent but annoying.

the red matrix server is configured with french as a main language.
and depending the browser i see it in eglish or in french

on mobile devices : everything is shown in french which is quite good

on firefox desktop : everything stays in english which can be a problem for some users.

chrome desktop : translation is fine

maybe the best thing is to add a function to put the red matrix language as the browser configuration

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#122
