### ISSUE TITLE
Email notifications not sent on mention if profile name different from channel name

### ISSUE THREAD

**Issue by solstag** [friendica/red#466]
On line 2441 of include/items.php we decide wether a term is a mention:

```
if((strcasecmp($term['term'],$u[0]['channel_name']) == 0) && link_compare($term['url'],$link)) {
        $mention = true;
```

The first element of the conditional takes the profile name (from `$term['term']`) and compares it to the channel name (from `$u[0]['channel_name'])`).

So if the user ever changes their main profile name while keeping their channel name, or if they expose a different profile with an alternate name to the sender, the mention is not found and the user never gets notified.

From what I understand, comparing the URL, as done in the second element of the conditional, should suffice.

Or is the name comparison there for a reason, and we should find a way to get the corresponding profile info and compare it, instead of comparing with the channel_name?

For now I've removed the name comparison from my instance. If nothing too ugly happens will make a pull request tonight.

Ni!

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#205
