### ISSUE TITLE
proposal for contact inviter

### ISSUE THREAD

**Issue by xavierle** [friendica/red#472]
this is more an idea of possible additional function than a real issue.

actually social networks grow by invitation amongs friends.

red include actually an invitation function which is indeed working but quite limited : you have to type emails one by one to send the invitations.

many  opensource CMS are using the following piece of code to add plugins for true invitation service (getting emails from webmail providers or other social networks)

http://openinviter.com/

maybe this would be later a good thing to integrated in red.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#124
