### ISSUE TITLE
Red Matrix setup page not showing with anabled mod_rewrite

### ISSUE THREAD

**Issue by tluther** [friendica/red#476]
The Red Matrix installation script seems to have a new bug, it does not display when mod_rewrite has been enabled. I could reproduce this on 3 different Debian Wheezy servers and one Arch Linux host.

This is what I did: 

Basic Debian GNU/Linux 7.5 "Wheezy" installation

installed the requirements:
aptitude install apache2 libapache2-mod-php5 php5 php5-mcrypt php5-mysql php5-gd mysql-server mysql-client
aptitude install php5-curl
a2enmod rewrite

At this point the Red Matrix Server - Setup page is still displayed.

and restart apache.

But as soon as I change /etc/apache2/sites-available/default from

[code]
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride none
                Order allow,deny
                allow from all
        </Directory>
[/code]
to
[code]
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>
[/code]
this page does no longer laod.

If I change "all" back to "none" it does load again as quickly as expected, but prevents installation, as well as expected. :)

I switched apache's error log to debug mode but got nothing.

access.log says for example: (urls and ips obscured), but this appears to be not realted IMO.

[Sat May 31 16:21:49 2014] [error] [client 1.1.1.1] File does not exist: /var/www/red/ping, referer: http://mydomain.net/
[Sat May 31 16:21:49 2014] [debug] mod_deflate.c(615): [client 1.1.1.1] Zlib: Compressed 277 to 213 : URL /ping, referer: http://mydomain.net/
[Sat May 31 16:21:51 2014] [error] [client 2.2.2.2] File does not exist: /var/www/red/test
[Sat May 31 16:21:51 2014] [debug] mod_deflate.c(615): [client 1.1.1.1] Zlib: Compressed 8715 to 2209 : URL /index.php
[Sat May 31 16:21:52 2014] [error] [client 1.1.1.1] File does not exist: /var/www/red/view/theme/redbasic/php/style.pcss, referer: http://mydomain.net/
[Sat May 31 16:21:52 2014] [debug] mod_deflate.c(615): [client 1.1.1.1] Zlib: Compressed 307 to 231 : URL /view/theme/redbasic/php/style.pcss, referer: http://mydomain.net/
[Sat May 31 16:21:53 2014] [error] [client 1.1.1.1] File does not exist: /var/www/red/ping, referer: http://mydomain.net/
[Sat May 31 16:21:53 2014] [debug] mod_deflate.c(615): [client 1.1.1.1] Zlib: Compressed 277 to 213 : URL /ping, referer: http://mydomain.net/
[Sat May 31 16:22:33 2014] [error] [client 1.1.1.1] File does not exist: /var/www/red/ping, referer: http://mydomain.net/
[Sat May 31 16:22:33 2014] [debug] mod_deflate.c(615): [client 1.1.1.1] Zlib: Compressed 277 to 213 : URL /ping, referer: http://mydomain.net/

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#123
