### ISSUE TITLE
Calendar event not visible in my own calendar

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#477]
I created an event on June 6th at about 10am as a test, the event started at 0000 and ends at 2359 on June 6th. I checked the adjust to viewer's timezone, then filled in the title and description and location fields and posted the event. Notifications about the event became available, but the event is not visible my calendar, unlike other events from other people. Am I doing something wrong, expecting something wrong, or is there something wrong here?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#206
