### ISSUE TITLE
Dirsync hub clean up "works with bugs"?

### ISSUE THREAD

**Issue by ghost** [friendica/red#478]
A directory sync has run somewhere, and I've got some dead hubs flagged.  In the hubloc table, all the dead channels are, indeed dead.  So far so good.

However, all the updates in the update table from zothub have flags of 4098 or 4099, including channels that definitely exist.

You probably know all this, but that's what it looks like from this end, anyway.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#207
