### ISSUE TITLE
Private message thread - only partial clone

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#484]
1. Send a private message from one of your channels on one Red hub to someone.
2. Receive their private message answer in your channel at the original hub OR as a private message in your cloned channel at another hub.
3. Reply to the received message at the cloned channel.
4. Receive their answer at any hub.
5. Confuse yourself when viewing the dialogue from the original hub - you get the recipients responses, but not what you wrote at the other hub.

Is it possible to make the entire private message thread clone between cloned channels?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#125
