### ISSUE TITLE
Ignore / Block strangenesses

### ISSUE THREAD

**Issue by zzottel** [friendica/red#510]
Blocking and ignoring only works partly.

_Parts that work as expected:_
If I as a blocked or ignored channel directly look at the channel in question, I get permission denied or see the posts but can't comment even if commenting is open to the whole network.
Blocked contacts don't get new posts, ignored contacts do.
If a blocked or ignored user comments a post (see below), this comment is not sent on to other contacts that can see this post.
A post that is received by an ignored user does not have PERMS_W_COMMENT set.
New posts by blocked/ignored users are not received by the one who blocks/ignores them.

_Parts that don't work as expected:_
Although in item_flags, PERMS_W_COMMENT is not set, the ignored user gets a comment box and can comment.
When he does, this comment is delivered normally to the original poster who also gets a notification for it (but is not relayed to the original poster's contacts as already stated above).
The same is true for blocked users who comment on older posts they got when they were not yet blocked.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#213
