### ISSUE TITLE
tags, categories and keywords

### ISSUE THREAD

**Issue by msooon** [friendica/red#528]
would it be possible to merge tags, categories and keywords
from logical point of view they should be all the same

It would also helpful to have a hierarchical structure like in some cms systems (e.g. drupal, wordpress)
For example if you choose tag linux you also get debian.

and alias for tags/categories 

for my personal use I built a system working this way:
http://msoon.bplaced.net/IN/video/infosystem.webm

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#126
