### ISSUE TITLE
message/mail autocompletion sometimes fail

### ISSUE THREAD

**Issue by msooon** [friendica/red#538]
It seems there is a problem with autocompletion.
I have two channels A and B.
connecting A to B. Then B to A. (both with full sharing - mail is marked) 
If I try to send a Message from A to B autocomplete doesn't work.
I saw a connection of two channels has two lines in abook.
The problem is that the value of abook_their_perms in line with abook_channel A doesn't changes after B connects to A.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#130
