### ISSUE TITLE
@mentions broken after re-editing post

### ISSUE THREAD

**Issue by ghost** [friendica/red#542]
This is an old bug, but I think its important enough to create an issue for it. 

When you edit a post after publishing (users have to enable this in feature settings) @mentions will be unlinked and loose their function. They’re only text. As a consequence @mentions+ are removed from the remote channel. 

So to make sure @mentions  keep working, users have to add the @mentions again when they re-edit the post.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#221
