### ISSUE TITLE
Bootstrap html font-size too small

### ISSUE THREAD

**Issue by ghost** [friendica/red#545]
_I also mentioned this in Channel One, but there was no respons, so let met do it the right way._

Bootstrap is updated to version 3.2 in Red.

There is one change that bothers me. It's about the root font size. Very important.
Here are the changes:

``` css
html{font-size:62.5%;}
```

to>

``` css
html{font-size:10px;}
```

The old one was 62.5% of the font size of the users web browser. For me personally that was 62.5% of 22px=13.75px. The new one is 10px. Ignoring the users browser settings, but even worse: it makes the whole Red application too small. Especially when the user has not set a minimum font size for his/her browser (that is a default setting for all browsers). Off course this depends on the users resolution, but when you have a large monitor (e.g. I have 1920x1080) it is just too small. Off course a user can set the minimum font size and change the font sizes in Red's display settings (I have to change it again now with the new 10px setting), but as a default it's too small.

I suggest to change it to:

``` css
html{font-size:100%;}
```

This will respect the users browsers settings. 

When this is done I advise to change other font sizes with the rem-unit (e.g. 0.8rem for the application and 1.0rem for the content). (or the em-unit, but that is more tricky, but better supported by older browsers)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#223
