### ISSUE TITLE
sys channel - possible eavesdropping

### ISSUE THREAD

**Issue by ghost** [friendica/red#546]
Hey all,
           [/channel/sys] It looks like after 3 months the World can read RedMatrix's members publications through it by scraping through our public hubs. I feel this is a privacy/security/safety issue we should adress rather quickly...

-----------------------as published on zotid.net/channel/ping

Example:
# ^https://red.vilarejo.pro.br/channel/rafaelamelo  --> has decided to not share her profile pictures with the world ...but..

you still can find her posts here :
# ^https://redmatrix.nl/channel/sys

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#224
