### ISSUE TITLE
Red: Bugs

### ISSUE THREAD

**Issue by GutHib** [friendica/red#55]
Hi,

Downloaded Red last night and very excited to take it for a test run. Found three bugs so far (more to come):

Uppon creating a channel, I received the following error message (channel was created just fine, though):

Warning: openssl_sign() expects parameter 4 to be long, string given in /home/netporg/domains/netpourri.org/public_html/include/crypto.php on line 10

Upon clicking on "friends" (at least if you don't have any):

Warning:  Invalid argument supplied for foreach() in /home/netporg/domains/netpourri.org/public_html/include/group.php on line 305

Also, the registration welcome mail contains all variables in an unresolved fashion (e.g. Hello $[username]).

Thanks for all the hard work you put into this!

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#18
