### ISSUE TITLE
Import/export profiles

### ISSUE THREAD

**Issue by ghost** [friendica/red#551]
I was just wondering if it would be difficult to export and import profiles? I'm talking about the actual profiles and import/export from/to different channels. You can clone profiles to a new profile, so maybe that output can be diverted to an export file.

The reason I'm asking is that I have a profile on one channel that I also want to use (with some modifications) on another channel.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#227
