### ISSUE TITLE
Show useful error messages in the cloud for too large files

### ISSUE THREAD

**Issue by zzottel** [friendica/red#552]
I just tried to upload a 24M video to my cloud using the web interface and ran into some problems that didn't show any useful error messages. If it's possible to throw good error messages at this point, it would be very nice if that was done.

1) If post_max_size in php.ini is set to a too small value (was 8M in this case), SabreDAV throws an XML error message that says it doesn't have a handler for this POST method.
2) If post_max_size is large enough (I set it to 100M), but upload_max_filesize is too small (default was 8M, too), Red just silently returns without doing anything or displaying an error message. I.e. the current cloud directory is shown, but with no new contents that should have been uploaded.

Additionally, setting the maximum image size on the admin page doesn't seem to have an effect on uploading a video. I'm not sure if this is intended, i.e. this size really only applies to images, so I just mention that. (Set it it to 10,000,000 and could upload the 24M video nevertheless.)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#131
