### ISSUE TITLE
Delivery problems with "more or less public" comments?

### ISSUE THREAD

**Issue by zzottel** [friendica/red#555]
Writing that here because I suspect nobody but Jake might be able to read my comments:

See thread https://indigoconsultant.com/channel/red/&f=&mid=632583a33c295dbd66b8b5b55892f6253b30ad34d4e3b07a5e0d43a6c5a395f0@indigoconsultant.com 

On zottel.red, I can only see Jake's comments, not Thomas'.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#228
