### ISSUE TITLE
Locks not telling the truth

### ISSUE THREAD

**Issue by zzottel** [friendica/red#558]
If on a thread that is completely open to the internet someone comments who has his channel privacy settings set to stricter options, the comment is shown with a lock.
In fact, though, this comment is not restricted and can be viewed by anyone on the internet. (Tested with a thread on parlementum.net which was at version 2014-08-07.760R+9a16955.)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#230
