### ISSUE TITLE
RSS feed for a channel

### ISSUE THREAD

**Issue by ghost** [friendica/red#571]
Please add an user friendly option to generate an RSS feed for your channel. This is especially important when using the channel for   publications (aka blog).

_Edit: this is something else as the existing redmatrix.nl/feed/channelname. That is about public activity, this new issue is about having only a feed for new (top) posts. But because a feed mechanism is already present, I don't think it would be that difficult to implement._

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#233
