### ISSUE TITLE
Private forums and new connection posts

### ISSUE THREAD

**Issue by zzottel** [friendica/red#573]
Restricting @-mentions+ posts to default permissions seems to work, with one little glitch:

The forum is configured to post a notification when a new connection is accepted.

If the forum is configured with no default permissions, but restricted access to public posts, the new connection post is posted with completely public access, thus exposing the connections that are configured to be hidden from everyone but forum members.

If the forum is configured with default permissions to a collection, the new connection message is empty.

Plus, when I click the lock at a forum message that was restricted to the collection (doing that at the receiving channel, not at the forum itself), I get an empty popup.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#234
