### ISSUE TITLE
System channels never get delete signal

### ISSUE THREAD

**Issue by ghost** [friendica/red#578]
This might actually be what's happening in #546 

When a post is deleted, the delete signal never makes it back to the system channels.  Therefore a deleted public post will still show up in search - even though we do filter it, ITEM_DELETED is never set for the sys chans copy of any item.  

I think this is because it's not in the recipients in drop_item(), but haven't followed that through the logs.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#235
