### ISSUE TITLE
Chat room - input out of screen

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#580]
Upon creating and entering a chat room the room visitor and the chat input textbox is out of screen, and the user must scroll to even start and gives the room a broken appearance - at least on my screens. 

How about this: 

1) the chat is as high as the last comment in the chat. If there is no comment, the input textbox is on top. The chat input textbox is only as low as the hight of the last comment in the chat pushes it down. If you want earlier comments, you must scroll, i.e. only the last comment is visible without scrolling.

2) Profile image of visitors in the room are flush with the top bar, newly arrived users go to the top of the list.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#133
