### ISSUE TITLE
Add styling of background colour of the generic content wrapper in theme settings

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#585]
I have a complex background image in my haakon-channel, with lots of different green colours. Posts and a number of widgets are possible to style already, and I have made these into shades of green that I like. However, several pages are actually mostly unreadable, notably the profile page, files page, web pages and the settings pages.

I believe it is CSS-styling of the class "generic-content-wrapper" which needs fixing, so if this can be added to Theme settings along with "Navigation bar background color", then this issue will go away for anyone using background images.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#237
