### ISSUE TITLE
Complex delivery chains

### ISSUE THREAD

**Issue by ghost** [friendica/red#59]
If a private channel (any channel with "Can view my "public" stream and posts" set more restrictive than "Anybody in this network"), cross posts to a public channel (any channel with "Can view my "public" stream and posts" set to "Anybody in this network"  or public) using an @- mention, the top level post is delivered correctly.  

If the private channel has private photos, viewers of the public channel will not be able to see the photograph.  I see this as permissions working properly, however, it was perceived as a bug the first time it happened in the wild.  Probably not worth fixing that yet if photos need to be reworked anyway.

But more importantly, the delivery chain is broken.

Observers of the new thread who have both channels in their contacts will see all comments.  

Observers of the private channel only will also see all comments.  

Observers of the public channel only will see only those comments delivered by the public channel in their matrix - they won't see any comments made by observers of the private channel only.  Oddly, they _will_ see comments from the private channel itself - just not from it's observers.

All posts are visible to everybody when viewing the public channel's page.  The issue is only comments not appearing in an observers matrix.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#20
