### ISSUE TITLE
Complex delivery chains: Choose the one with most permissions

### ISSUE THREAD

**Issue by zzottel** [friendica/red#594]
I recently had the problem that I couldn't comment on a post that was sent to a public forum because I was among the contacts of the author but wasn't allowed to comment on his posts. I would have been allowed to comment on the forum's posts, of course, but as the direct delivery reached my hub first, this version of the post was shown, and I couldn't comment.

This is probably a very rare case right now, and it also was a mistake by the author and I'm allowed to comment his posts now, so there's definitely no need for an immediate fix.

I thought I'd write it down here, though, because this might be of more importance in the future, should there ever be "celebrity accounts" that don't allow commenting to most of their contacts.

Could it be possible, in the event that a top-level post reaches a hub that is already there and has come in via another delivery chain, to compare permissions for both posts and replace the already existing one with the new one if permissions are more open?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#134
