### ISSUE TITLE
Adding weird RSS-feed failed

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#599]
I have never seen an RSS-feed URL like this before. Firefox manages to show it, but I cannot add it at Parlementum running version 2014-09-19.803R+278da6a.

http://www.orsta.kommune.no/RssFeed.aspx?ObjectType=Article&Filter=Category.ParentID%3a592+Category.ID%3a592&Title=Nyheiter%20-%20Orsta%20kommune&Description=Nyheiter%20-Orsta%20kommune&OrderBy=@CategoryRelation.Approved%20DESC

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#241
