### ISSUE TITLE
Ignore channel on all channels, show in collection

### ISSUE THREAD

**Issue by ghost** [friendica/red#614]
I sometimes connect to a channel that has a stream that updates very often. This makes the matrix unusable, so I have to ignore or even remove that channel. 

What I like, is still be able to watch that stream, but only if I view the collection where I've put it in. In other words: ignore the channel like we do now, but show it in the collection(s) where it's part of.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#242
