### ISSUE TITLE
File permissions are accidentally reset 

### ISSUE THREAD

**Issue by ghost** [friendica/red#615]
Steps to reproduce:
- Create a folder in the root of your files (cloud/).
- Click on edit (pencil icon)
- Click on permissions (open lock icon)
- Select one or multiple collection(s) or channel(s)
- Click Close or click outside the ACL window
- The lock icon is now closed
- Click Submit
- Your back in the root of your files
- Click again on edit
- The lock icon is still closed
- Click now on Submit
- Click again on edit
- The lock icon is open!
- Click on the lock icon and you see that all permissions are gone.
- The expected behaviour is that permissions are unchanged, cause you didn't edit the permissions.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#243
