### ISSUE TITLE
Unify remote auth and local login

### ISSUE THREAD

**Issue by pafcu** [friendica/red#629]
Currently there are two ways of "logging in", depending on if the site you are using is a remote host or your home hub. This is a bit confusing to users, since you have to remember which button to press (and it makes the UI a bit more complex).

A simple solution would be to move the content on the remote auth page to the login page, which would remove an extra button from the UI. This means that the user would click "Login" on both remote hubs and the home hub. However, the login page would be a bit messier in that case. Probably it's worth to have a slightly more complicated login page to simplify the UI everywhere else.

Another option would be to always login using a channel address (instead of an email address like now). If the address looks to be a remote address, things would work like the current remote auth page, but if it looks local an additional password field would be displayed, so things would work like the current local login (except using an channel address instead of an email address). The risk here is phising: a nasty hub could display the password input box despite the user entering a remote address, and the user then types in their password out of habit, or because they didn't realize they actually aren't on their home hub.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#245
