### ISSUE TITLE
Source Route Checking

### ISSUE THREAD

**Issue by ghost** [friendica/red#633]
This issue is mostly for the sake of keeping issues in one place - not expecting it to be perfect immediately.  So far it mostly works.

Wall to wall posts (comments) are presently broken - because they have no route.  Don't know if they'll be picked up by the poller or not yet.  They do get stored, and [correction] do get distributed, but get rejected.

And another correction - it seems it's not that straight forwards.  Reproduced this three times, and then once more where it was fine.  So this is a shit bug with nothing to see, but will leave it open as a top level post.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#246
