### ISSUE TITLE
Remove 680px in mod_apps.css

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#634]
When you login at most hubs you are taken to the default channel of the account and the page https://domain/apps . Portrait mode smart phones and even some landscape mode smart phones (vertically/horizontally held phones) do not display the entire "frame" with apps. Using the browser inspector, I think I have found the problem in mod_apps.css, which contains a fixed 680px rule. Turning this off seems to give better results. However, there is a comment in the CSS, which might indicate things are not as easy as that.

/\* Comment out to see why.  If you've got
a better idea, go for it */
.generic-content-wrapper {
width: 680px !important;
}

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#247
