### ISSUE TITLE
Where to ask why I don't recieve a verification email?

### ISSUE THREAD

**Issue by rolfdeenen** [friendica/red#635]
After quite some struggeling, I managed to install redmatrix on my homeserver. However, when I try to register myself I do not recieve a verification e-mail. I supose that's the reason I can not login. I soon realised that I had not set an smtp-server anywhere, which I suppose is necesarry for sending email. This goes for a remote (gmail) email address and for a local (local domain) email address.

I have come here because I've been unable to find any documentation concerning configuring email and smtp. I tried searched for email and smtp on google, duckduckgo, github and did a grep on the "www" directory of my server.

I appologize for possibly mis-using this space for something possibly not belonging here but decided to do it anyway as I see no other way to go with this issue. I hope someone can point me in the right direction, either with the email question or where to ask this.

Kind regards,
Rolf Deenen

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#248
