### ISSUE TITLE
Show reason for unverified posts

### ISSUE THREAD

**Issue by pafcu** [friendica/red#639]
It seems that most posts are verified. It would, therefore, be better to alert the user when a post ISN'T verified, and simply not show anything special when everything is OK. Additionally, it would be good to identify why a post was not verified:
a) Because it's a wall-to-wall post. These can not be verified. Show a yellow checkmark with a tooltip like "This is message is a wall-to-wall post. It is not possible to prove the author of this type of message."
b) Other issue. Potentially someone is trying to impersonate someone else. Show a red x to alert the user something is wrong. Show a tooltip like "Verifying the sender of this message failed. It is possible that the message is not from the claimed author."

Summary: Don't show any special sign that a post is verified, do show a sign when it's not, and indicate the reason why it is unverified.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#249
