### ISSUE TITLE
Filter by channel type in directory

### ISSUE THREAD

**Issue by pafcu** [friendica/red#640]
The channel directory would be a lot more useful if it would be possible to filter by channel type, i.e. personal profile, forum, feed repost, etc. This would make it easier to find interesting content, since it's probably much more likely that users browse for interesting forums that they want to join, rather than connecting with random people.

An easy way to do this would be via keywords: currently when a new channel is created it's possible to select a Channel Type. Based on this type a keyword would be added to the new channel, indicating whether it's for social networking, a forum, a feed republish, etc. In the channel directory it would then be possible to filter according to these keywords.

Filtering by keyword is already supported, the only new thing that's needed is to automatically add an appropriate keyword to a new channel. Additionally, it might be nice to have explicit support in the UI for filtering by channel type separate from the other keywords, since otherwise they might dominate too much the keywords cloud shown in the channel directory.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#137
