### ISSUE TITLE
Clones and archived / unarchived connections

### ISSUE THREAD

**Issue by Drammen** [friendica/red#641]
For some reason Mike had become archived. I have been hanging out at Parlementum.net lately, and suddenly he disappeared from my contacts. I found him again, he had become archived there, so I unarchived him again, and now I could @-tag him. However, I logged into Friendicared.net and the same connection along with most others were all archived. The connection change is perhaps not cloned?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#250
