### ISSUE TITLE
Facebook RSS-feed with HEX code for æ, ø, å - possible to fix?

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#643]
Facebok RSS-feeds are broken as Norwegian characters are shown in the RSS feed as HEX code - could be a client issue upon publishing - I do not know.

https://www.facebook.com/feeds/page.php?format=rss20&id=164212400389793

å becomes &xe5; rather than a regular Unicode character or &aring;.

http://www.htmlandphp.com/reference/html-special-characters.html

Is it possible to display these correctly if sourced in Red?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#138
