### ISSUE TITLE
On admission to new node, import channel from other node leaves account broken

### ISSUE THREAD

**Issue by gordon-morehouse** [friendica/red#647]
Hi there, I recently set up an identity on one RedMatrix node to look around, and then found they had a really crappy SSL cert, so I got invited to a different node. Once I logged in after being approved, I was presented with the usual "create a channel" thingy (which really needs some more "WTF" type microcopy or tooltips since you can't really expect users to RTwholeFM before logging in to poke around).  I noticed the "import from another location" option and decided what the hell, I'll give it a try.  So I typed in my_identity@other.node.fqdn and the login email and password, and I got a couple non-errory status notifications in the upper right.

But, what was actually created was a broken channel/identity on the new server of some kind.  It insists the channel name is "@new.node.fqdn" (nothing before the @), some pages tell me I need to log in and access denied even when I'm logged in (and the logged in state doesn't change on those pages - on others, I get no errors and stay logged in, i.e. the affected pages don't log me out).  It did not appear to import my avatar or anything else.

I'd prefer not to reveal the identities publicly but I will poke around and add a comment with more specific observations of brokenness shortly.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#140
