### ISSUE TITLE
implement deletion of community tags

### ISSUE THREAD

**Issue by friendica** [friendica/red#65]
According to the original community tag spec, anybody can remove their own community tag and it will be removed from the post/item it is attached to. This event propagates to all stream listeners. 

It is removed by deleting the corresponding community tag activity item. ("Bob tagged Violet's post with #octopus") 

Additionally, the post owner can remove any tag of their content using the same method.

This needs to be implemented in Red and tested.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#25
