### ISSUE TITLE
RSS-feed - link problem in matrix notification

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#653]
https://parlementum.net/channel/politikk sources all 77 RSS-feeds from the Norwegian government's two sites - Stortinget (parliament) and Regjeringen (executive). 

The network page of the channel has a matrix-icon which displays notifications.

When clicking a notification from an RSS-feed under the matrix-icon, I arrive at an empty page without leaving the hub. 

I expected to either see the RSS-feed item in the network feed (anchor) or be taken to whatever page the RSS-feed is pointing to. Is it a setting I am missing or is this a bug?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#143
