### ISSUE TITLE
Lady Bug suggestion - check for Red hub version and commit it and include automatically

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#656]
In the Help-menu of KDE, it is possible to file an application bug. When you do, you presented with a dalogue stating which application you are in, version, OS and so on, and a text explaning this info will be included if you continue to report the bug.

By including the Red hub version and the commit id when a user hits the Lady Bug, the developers have important information automatically and do not have to ask. Perhaps the issue is already resolved and the answer is simply PULL.

https://developer.github.com/v3/issues/#create-an-issue describes how to create issues on Github.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#144
