### ISSUE TITLE
Deleting clone sets xchan_flags deleted

### ISSUE THREAD

**Issue by ghost** [friendica/red#657]
When you delete a channel from a secondary hub, we set XCHAN_FLAGS_DELETED whether or not it's a local delete.

This is because we, well, set XCHAN_FLAGS_DELETED whether or no it's a local delete.  I think we just want to delete line 294 to 297 of include/Contact.php but since it's deletion, here's an issue first to check.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#261
