### ISSUE TITLE
multiple profiles not working

### ISSUE THREAD

**Issue by friendica** [friendica/red#66]
We had envisioned a different approach to multiple profiles in Red than in Friendica - whereby profiles would more closely correspond to privacy groups. We also need to refer to these internally by hashes instead of a simple id so that they are system independent and not require translation across identity instances. 

The aligning with privacy groups (collections) poses a bit of a problem because channels can belong to multiple privacy groups. They should be directed to one profile - probably from a choice of those groups they belong to, the choice being made on the connection edit page.

It is also not clear how these profiles initially get populated and with what data, if they are created when a privacy group is created. 

The problems with this approach may be worse than the old method - where any channel could be assigned to any profile and profiles created at any time for any purpose. Would consider bringing back the old behaviour as a temporary solution; as long as it uses hash identifiers instead of simple numeric ids.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#26
