### ISSUE TITLE
Add collections to @ and @! popups

### ISSUE THREAD

**Issue by ghost** [friendica/red#666]
When someone want to restrict their post to a collection they now have to use the ACL selector. Like posting to forum channels it would be great if we can also use @!collection to restrict the post permissions to a specific collection.

It would also be great if we can use @collection to distribute the post to the collection members only (so not to others their network/matrix page), but without changing the permission. So if non collection members can still see it on the channel page. This makes it possible to distribute a post to specific members (e.g. who speak Dutch), but with the option to keep the post public (or e.g. restricted to Red members only).

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#264
