### ISSUE TITLE
HELP: Deleted all channels on my hub

### ISSUE THREAD

**Issue by ghost** [friendica/red#667]
I opened by accident all the channels on the channel admin page on my hub, incl. the delete button. Now they are all gone. I have a a DB dump from last Thursday. Should I restore that? Or are there other ways to fix this extremely STUPID error I made?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#265

**Comment by tazmandevil** [comment]
On Sat, Apr 04, 2015 at 04:47:44PM -0700, jeroenpraat wrote:
>    This issue was moved to [1]redmatrix/redmatrix#265
> 
>    —
>    Reply to this email directly or [2]view it on GitHub.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    1. HELP: Deleted all channels on my hub
> 	https://github.com/redmatrix/redmatrix/issues/265
>    2. https://github.com/friendica/red/issues/667#issuecomment-89689838
>    3. https://github.com/friendica/red/issues/667#issuecomment-89689838

I hope you had a DB backup...

./taz
--
https://red.liberame.org/channel/tazman

**Comment by jeroenpraat** [comment]
Fortunately I had. ;)
