### ISSUE TITLE
Extreme loads and /post bombardment

### ISSUE THREAD

**Issue by zzottel** [friendica/red#669]
I had to disable the red.zottel.net and zottel.red hubs on my server because the load went up to a friggin 480. (It's amazing how usable the VPS stayed in command line terms.)

It started about half an hour after I updated to current git. red.zottel.net bombarded itself with requests to /post. I then disabled red.zottel.net, thinking it might be an issue with the fact that there's a clone there of my zottel channel at zottel.red. It seems to have started when I liked the git's post about the new feature of fetching unknown parent posts. (I liked it at as zottel@zottel.red, and the git channel is hosted at red.zottel.net, where there's also a clone of zottel.

But then the parlementum hub started to bombard zottel.red with requests to /post, too, so I switched zottel.red off, too.

I'll see what I find in the logs and add that here.

**Comment by jeroenpraat** [comment]
Moved to redmatrix/redmatrix#266.
