### ISSUE TITLE
Birthday in profile defaults to November 30 1999 (1999-11-30)

### ISSUE THREAD

**Issue by ghost** [friendica/red#670]
When editing a profile and saving it, the Birthday gets a default of  November 30 1999 and an age of 14. Without touching it. Only when manually empty it again and press submit it's gone. But when you edit the profile again 1999-11-30 is in the birthday field again. Pressing submit starts the problem all over again.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#267
