### ISSUE TITLE
(Unverified) channel settings not being synced with initial clone

### ISSUE THREAD

**Issue by ghost** [friendica/red#672]
This is unverified.  I'm making an issue so it doesn't get lost.

There are inconsistencies between the content arriving at newly created clones, and also in the "inherited" permissions for new connections.  IE, permissions don't match if they haven't already got an abook entry.

Clicking submit on the settings page at the primary hub fixes it.

Ergo, I think we're missing a packet to sync the channel table.  Having a quick look at the code, it at least looks like we only sync the guid, hash and address.  Will take a closer look when I get a chance.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#146
