### ISSUE TITLE
Limit number of matrix notifications

### ISSUE THREAD

**Issue by ghost** [friendica/red#673]
Now with Diaspora federation I have sometimes more than 1000, 2000 or more new matrix (/network) notifications. How higher the number how longer it takes to open them and mark them as seen. What is the function? I can understand that there is a function with lower numbers, but now it's getting useless IMHO.

I suggest to limit the number to, let's say, 100. More than that will read as 100+. Another way to do it is to make it an option of course.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#268
