### ISSUE TITLE
Validation for homepage field

### ISSUE THREAD

**Issue by pafcu** [friendica/red#683]
Currently it's possible to enter javascript into the hompeage field, which is run if the user clicks on a link pointing to the homepage.  I suspect that in most places the URL of the link is shown as the text of the link, so the user can actually see that the link executes javascript. However, it' still a bit of a risk. Additionally, there might be links with the javasript in the href but some other text as the link text.

To avoid typos, it might anyway make sens to validate entered URLs by trying to download the specified page to check that it really exists.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#269
