### ISSUE TITLE
Channel theme overriden by hub theme

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#684]
A public channel which does not require logging in is available to the Internet at https://parlementum.net/channel/flldrammen . The channel is themed to be in as close accordance as possible with a profile guide from an organization, which everyone in the organization has to abide by. 

The channel has a word cloud with hashtags, and when a user clicks one of these hashtags a search result is displayed, but using the hub's theme and not the channel's theme. 

The navbar belongs to the hub and not the channel, which is confusing. 

- the registration takes you to the hub's registration page with the hub's theme. One idea might be to notice if people came from a channel page to the hub's registration page, and explain to them something like "To connect to [channel you came from], you need to register here first." 

- The house icon takes you to domain/ and not domain/channel/channelname as one might expect. One idea - a Hub house and a channel House?

- App icon - shows hub apps, not channel apps.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#147
