### ISSUE TITLE
Browser stops the Share/Submit post button from working

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#688]
Share/Submit-button does not work in Iceweasel/Firefox 35 anymore - expect fewer posts till this is fixed, it does work in Konqueror 4.8.4, so something is broken either in Firefox/Iceweasel or in RedMatrix at the hubs Parlementum, Friendicared and ZotID.

I have Iceweasel version 35.0a2 (2014-10-17) on my laptop, but the same problem occured earlier in my Firefox for Android.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#270
