### ISSUE TITLE
SSL certificate validation failing

### ISSUE THREAD

**Issue by anaqreon** [friendica/red#694]
I purchased a new Comodo SSL certificate from SSLs.com for the new subdomain I created for a new Red Matrix hub. I cannot install the hub, however, because it claims that the SSL certificate cannot be validated. I have tried installing from scratch (dropping database, re-cloning the red repo) multiple times without success. This certificate is the same brand and type of certificate I used with my previous Red Matrix instance a few days ago, just issued for a different subdomain. Any ideas?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#271
