### ISSUE TITLE
Sslify doesn't forward the content-type as expected, breaking the display of some formats

### ISSUE THREAD

**Issue by solstag** [friendica/red#704]
Originated from a discussion here: https://mobiliza.org.br/channel/aleabdo/?f=&mid=a6c6fded7ac531085230de65e8a0358b5fd7412a5912132937bdc5a5c760b88d@mobiliza.org.br

Sslify is not forwarding the Content-Type as expected, see

```bash
curl -I "https://mobiliza.org.br/sslify?f=&url=http%3A%2F%2F2014.okfestival.org%2Fwp-content%2Fthemes%2Fokfest-2014%2Fimg%2Fokfest-logo.svg"
curl -I "https://mobiliza.org.br/sslify?f=&url=http%3A%2F%2Fi1.ytimg.com%2Fvi%2F6_nFuJAF5F0%2Fmaxresdefault.jpg"
```

Major consequence is: when the browser can't correctly guess the image type, displaying fails.

So for JPEGs it looks like it's working because the browser is smart enough to guess the type from the content. Also for an SVG loaded on its own. But it fails for SVG inside an <img> tag.

So this seems to need a fix.

Another thing would be to fix the file extension for people wanting to save the files that go through Sslify.

Currently if you change "/sslify" in the url to "/sslify/whatever.svg" it all works fine, so perhaps all we need is to change the sslify url generator to include the original filename before the parameters.

Note that if you fix the file extension issue, the issue with SVG also vanishes because the browser is now capable of guessing the Content-Type from the file extension, so this would be a workaround.

**Comment by pafcu** [comment]
Is this issue still valid or was it fixed by the commit mentioned above?

**Comment by solstag** [comment]
It's fixed, awesome. The other thing that could be improved is the thing about the file name and saving. I'm going to leave this open as I commit a patch I've already created for that. Thanks pafcu!

**Comment by solstag** [comment]
Done. Completely solved now =)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#255
