### ISSUE TITLE
SQL issues

### ISSUE THREAD

**Issue by habeascodice** [friendica/red#705]
After the postgres conversion a lot of the SQL was cleaned up but there still remains some pretty big warts. 
The 2 big ones being:
- Dates use some kind of constant for 'null' instead of using an *actual* null. There exists many places in the code and many sql statements that are way more complicated than they need to be just to avoid using SQL NULLs for some reason.
- table names and field names are needlessly quoted everywhere, when only 3 fields have reserved names (ignore, key, and with) -- all 3 could easily have far better names that aren't reserved, and no quoting would need to be done anywhere in the code.
There are others but I lost track of my list at the moment.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#149
