### ISSUE TITLE
Theme selection for regular and mobile - show list of available themes in both lists

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#71]
Under Display settings the user can select their preferred theme for regular PC and mobile, but there are currently no themes selectable under mobile, even though APW and the others work well on Samsung Galaxy Note 10.1 or Samsung Galaxy S III. Please let users select their preferred theme from what is available in both lists.

Another and related problem is that if I select APW as the regular theme, Basic will be shown in Mozilla Firefox on Android, unless I select "View as Desktop" in the browser's setting.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#28
