### ISSUE TITLE
Privacy leak when resharing tag+ posts

### ISSUE THREAD

**Issue by solstag** [friendica/red#714]
Ni!

1. Click to reshare an item posted @someforum+

2. Add a mention to @!someforum, or @someforum and use the ACL so only it can see

 (perhaps you want to privately call the owner's attention to an evil post on his wall)

3. The post ends up in the forum's wall!

 (seems like the + is being interpreted although it is within the [share] element)

I've frobbed with this and those seem to be the only cases where this happens.

**Comment by solstag** [comment]
Thanks for looking into this. After the last month of changes I can't reproduce this behavior anymore. No idea why :/ but if I recall correctly there were some changes to tag handling, so probably got fixed along the way. Closing :)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#257
