### ISSUE TITLE
outq not being processed

### ISSUE THREAD

**Issue by cyberczar** [friendica/red#716]
Hello. I've set up a new redmatrix instance at https://iamover18.net and I'm noticing that none of the posts are federating out (the outq table in the database is not being processed.)

Cronjob is set for php to call include/poller.php and I've manually run it several times from the shell.

No luck.

I've got a valid SSL certificate issued from Comodo, and SSL Labs gives the server/ site an "A" rating.

Any ideas?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#258
