### ISSUE TITLE
Loading of "Expand post" function causes display glitches on Firefox Mobile

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#719]
I believe this behaviour was introduced from August onward: 

Problem: upon loading a page with post or posts in Firefox Mobile, black or grey blocks - sometimes transparent, sometimes not, will appear over smaller or larger parts of the page.

At first, I only noticed it was erratic, and seemed to be tied to scrolling up and down.

Today, I was lucky to catch it at a fresh channel with a single post, and this post happened to display in its entirety first, at which point it looked as it should, and then it got contracted with an "+ Expand this post" in the middle, and now the black/grey problem appeared. 

I do not know if this is the only trigger for the problem.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#254
