### ISSUE TITLE
WebRTC in Red

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#72]
https://friends.mayfirst.org/display/marxistvegan/717970 announced that Tobias has made a WebRTC addon for Friendica, available at https://github.com/friendica/friendica-addons/tree/master/webrtc

WebRTC in Red can enable one-way or two-way audio and video channels for users with up-to-date browers.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#107
