### ISSUE TITLE
Content from adult channels is shown in Discover tab and in mod/home.php

### ISSUE THREAD

**Issue by zzottel** [friendica/red#736]
I wanted to try to fix that myself, but I found strange things and am not sure in which direction to go.

My plan was to set the currently unused item_flag ITEM_NSFW on every top-level post by a channel marked as adult and then filter using these items in home.php, in network.php (discover tab) maybe dependent on the current safe search setting.

What confuses me is that I don't see how a channel is marked as adult and what flag actually makes the difference. I thought it was the xchan_flags XCHAN_FLAG_SELFCENSORED and XCHAN_FLAG_CENSORED, but when I set the adult flag in the settings on a test channel, these flags did not get set. Instead, a channel_pageflag PAGE_ADULT is set which is never sent on to other servers/directories or used in any other way if I understand that correctly.

Safe search, OTOH, relies on the mentioned xchan_flags to be set.

Which is the flag to look at? Why doesn't making a channel an adult channel set the xchan_flags?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#275
