### ISSUE TITLE
White screen of death after the latest git pull.

### ISSUE THREAD

**Issue by ghost** [friendica/red#737]
After the latest git pull, I have white screens for login form and this error in the logs:
==> /var/log/apache2/error.log <==
[Fri Dec 12 08:26:26 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/directory
[Fri Dec 12 08:33:27 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:33:29 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:33:31 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:35:03 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:35:04 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:35:05 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:35:07 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/&JS=1
[Fri Dec 12 08:35:25 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/apps
[Fri Dec 12 08:35:27 2014] [error] [client xx.xx.xx.xx] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '' <-- \n  thrown in /var/www/library/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129, referer: https://gravizot.de/apps

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#276
