### ISSUE TITLE
Add explanation to Export Channel and Export Content

### ISSUE THREAD

**Issue by pafcu** [friendica/red#743]
The user is offered the option to export channel and export content in settings. However, it's not mentioned what the data is and what the user is supposed to do with it. Instead of having the links pointing directly to the json data, it would probably be better to display a page with some explanation and give the link to the json there. There is extra risk for confusion since the links are listed under "Settings" while they actually are not settings.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#278
