### ISSUE TITLE
Contact autocomplete doesn't work on remote hubs

### ISSUE THREAD

**Issue by pafcu** [friendica/red#750]
Contact autocomplete doesn't work on remote hubs since acl.php mostly works with local users. In the case where users allow others to see their contacts, autocomplete could be made to work on remote hubs as well, in a similar way as how the common connections widget works.

**Comment by pafcu** [comment]
Fixed.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#279
