### ISSUE TITLE
Mentions unreliably broken

### ISSUE THREAD

**Issue by ghost** [friendica/red#761]
There's something subtly wrong in the mention regex.  Sometimes, they just don't render.

I don't think it's the latest autocomplete changes, on the grounds that I don't use autocomplete, and it's equally broken with both implementations.

Simplest way to reproduce, mention with no body.

Second simplest way to reproduce, tag @test with a body of test.  This will fail even if it's an explicit tag like @test+123

Tag @test with a body of foo, and it'll work.

Seems similar to the smilies issue where :cat will match :cats and :catering if you're not careful.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#153
