### ISSUE TITLE
Integrating chat and private messages

### ISSUE THREAD

**Issue by redswede** [friendica/red#762]
Hi. Coming from facebook I like the possibility there to chat and PM without any distinction between the two forms. 
I see that chat right now is a plugin and not core. I wonder if anybody is maintaining this plugin and if there are plans to make it core?
I am new to red so I have no idea how much work is needed to integrate these two.
/cheers

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#281
