### ISSUE TITLE
Error creating new channel within the limits of the subscription plan

### ISSUE THREAD

**Issue by redswede** [friendica/red#763]
Got an error i top right corner little box:
"This action exceeds the limits set by your subscription plan." during my 4th channelcreation on redmatrix.nl despite the system telling me in the channel-manager-page that "You have created 3 of 10 allowed channels. "
{"version":"2014-12-23.898R","commit":"d1273b1"

private message from jeroenpraat:
===========================
Thu, 25 Dec 2014 - 10:42 AM
Number of channels allowed on the hub
--------------------------------------------------
That's very strange. This must be a RedMatrix issue, so can you ask this on the channel one forum, cause I don't have time the next two days.

**Comment by pafcu** [comment]
Was this issue fixed? Can it be closed?

**Comment by habeascodice** [comment]
Unknown. cvogeley's description is opposite of the reporters. See https://federated.social/display/3d763ad8f9788481387378a631a80be03ac3c2eb4b8e08fb39fdfb38a488fb4e@federated.social
Also, jeroenpraat's server is still undergoing a migration, so I don't think redswede is able to test again. I will run a test myself later tonight now that I have more time.

**Comment by redswede** [comment]
Correctly habeas RM.nl seems a bit unstable at the moment and therefore not really reliable for tests. I am busy at the moment and will not be able to test within the next week-10 days.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#154
