### ISSUE TITLE
Show language name instead of language code in language selector

### ISSUE THREAD

**Issue by pafcu** [friendica/red#773]
Currently only language codes are shown in the language dropdown in mod/lang.php. It would be better to show actualy language names. PHP has a semi-standard way of getting the language name from a code (used in get_language_name() in include/language.php). However, that way requires an extra library to be installed on e.g. Debian servers, so it's not really optimal, and is not currently used.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#284
