### ISSUE TITLE
[audio] tag not working when there are spaces in the filename

### ISSUE THREAD

**Issue by ghost** [friendica/red#774]
When an audio tag and audio file name is formatted like this: [audio]Artist - Song.mp3[/audio] the html5 audio player is not displayed (Firefox) or empty (Chromium). When you replace the spaces manually with %20 it works.  [audio]Artist%20-%20Song.mp3[/audio].

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#285
