### ISSUE TITLE
Feature Request: Provide ability for hub admin to specify default search query for Channel Directory

### ISSUE THREAD

**Issue by cyberczar** [friendica/red#775]
**Issue:** The Channel Directory [hub url]/directory currently defaults to displaying channels in an alphabetical order.

The order can be changed by modifying the drop-down selector in the theme to sort the results by Alphabetical (A-Z), Alphabetical (Z-A), Newest to Oldest, and Oldest to Newest, with optional flags for Safe Search and Public Forums.

Then specifying additional options, URL parameters are created and these variables are passed-back to the /directory module.

**Request:** Provide a configurable option (with or without a UI) to allow a hub admin to manually specify the URL parameters so when a user clicks on the Directory menu, RedMatrix will return the admin-specified results by default.

Of course the user can choose other options at will.

**Example:** ```util/config system directory_page_default "q=directory&order=date"```

Which would return all channels in a newest-to-oldest fashion by appending "?q=directory&order=date" to the URL by default, and upon first call.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#157
