### ISSUE TITLE
Default Cache-Control headers are WAY too short

### ISSUE THREAD

**Issue by cyberczar** [friendica/red#777]
In mod/photo.php, line 228 & 229 the default Expires and Cache-Control ages are set to 24 hours.

This is insanely low and defeats the purpose of using a content-delivery network to reduce bandwidth and load on the server.

Especially since red#matrix stores all user and profile photos in the database which is an expensive operation to retrieve blob objects from to begin with.

I propose the Cache-Control and Expires headers both be set to 365 days. ``3600*24*365``.

Even better, it should be configurable. :-)

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#158
