### ISSUE TITLE
Logging Out when on photo tab

### ISSUE THREAD

**Issue by ckasam** [friendica/red#783]
Everytime I open the photo tab, I am logged out.  I'm not sure if this is a settings issue, cookie issue, or something that my host is doing.  I my install is at red.sovereignradio.com using x10hosting.com 
There have been suggestions to change the paranoia settings, which I have done to no avail.  none of the other tabs such as the file, or webpage tabs do this.  It seems very specific to photo.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#159
