### ISSUE TITLE
error? in "install.txt"

### ISSUE THREAD

**Issue by mrpink86** [friendica/red#79]
in the "install.txt" there are a few lines confusing:

" make sure folder _view/tpl/smarty3_ exists and is writable by webserver

```
    `mkdir view/tpl/smarty3`

    `chown 777 view/smarty3`"
```

shouldn't it be like: 

" make sure folder _view/tpl/smarty3_ exists and is writable by webserver

```
    `mkdir view/tpl/smarty3`

    `chmod 700 view/tpl/smarty3`"
```

Because 777 is worldwide writeable and we only need that it is writeable from the webserver itself (so only 700), as written in the first line. and the "/tpl"-part was missing in the chown line. If its not an error ignore it, but I learned from an owncloud installation that you never should make a folder worldwide writeable.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#29
