### ISSUE TITLE
Don't show channel id after autocompleted contacts unless needed

### ISSUE THREAD

**Issue by pafcu** [friendica/red#824]
More often then not, using a simple @mention is unambiguous. It may be confusing for users that some mysterous sequence of numbers and letters are tacked on to the contact name. The code could be modified to check if there is more than one match with the same name, and only add the id in that case. The easiest place to do this is probably in autocomplete.js.

**Comment by solstag** [comment]
Another option would be to append the "@mention" with "@mention@server" whenever necessary, instead of adding the ID, as it already works and should be just as unambiguous.

**Comment by pafcu** [comment]
IMHO it's not a good solution because it gives the impression that that's the "correct" way of typing it. A newcomer types a name, autocompletes it and sees that it changed to another format. Naturally the person then assumes that that's the way it has to be written, and misses out on a nice feature (it's still slightly better than the current local id based one, since it can be used on remote servers too).

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#166
