### ISSUE TITLE
Content moves out of view when collapsing a long item

### ISSUE THREAD

**Issue by pafcu** [friendica/red#828]
After collapsing a long item it is sometimes necessary to manually scroll up so that you can continue reading whatever is after the now collapsed item.

This can probably be solved by taking the callback example code at http://jedfoster.com/Readmore.js/, but only scrolling up if the item is actually out of view (can be done e.g. with the code found at http://stackoverflow.com/a/488073).

It's a question of ~10-15 lines of code in total, most of which is given. You basically have to come up with one "if(...)" clause, and copy-paste the given code in the correct place (in the collapseHeight function in view/js/main.js).

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#168
