### ISSUE TITLE
Spaces in tags on photos spaces are replaced with underscores

### ISSUE THREAD

**Issue by pafcu** [friendica/red#834]
When adding a new tag to a photo spaces in the tag are replaced with underscores. Tags should be able to include spaces just like elsewhere.

According to Mike:
Historical reasons, but the tag replacement on submit code block is a copy/paste of an older version from mod/item so may need to be revised to match.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#291
