### ISSUE TITLE
Viewing event from calendar displays event info beneath colored bar representing event

### ISSUE THREAD

**Issue by pafcu** [friendica/red#846]
In the calendar, when an event is viewed, by clicking the colored bar in the calendar representing the event, the info is displayed beneath the bar. This can be fixed in CSS by adding a largish z-index for #colorbox.

**Comment by einervonvielen** [comment]
Tested to add 
    z-index: 9;
    opacity: 1;

to view/theme/redbasic/css/style.css
there

...css
    #colorbox {
        border: 0px solid $fancybox_bgcolour;
        top: 0px;
        z-index: 9;
        opacity: 1;
    }
...

Result
- z-index; 9; > Now it is above the bar > ok
- opacity: But its still opaque. So I tried to set it as you see. It changes but is still "quite" opaque. > not ok

**Comment by einervonvielen** [comment]
![bildschirmfoto vom 2015-01-16 23 30 46](https://cloud.githubusercontent.com/assets/7354052/5785587/a8eec5e6-9dd8-11e4-8b07-c449b7520ac6.png)

**Comment by pafcu** [comment]
It works fine for me, using Firefox. The problem is probably not transparency, it's the lack of a background color for some reason.

**Comment by pafcu** [comment]
Line 1033 in view/theme/redbasic/css/style.css sets the background color to $fancybox_bgcolour, which is set in view/theme/redbasic/php/style.php. Perhaps you have a bad value there? Can you open https://yourdomain/view/theme/redbasic/php/style.pcss in a browser and check line 1033 to see what was actually set as the background color?

Thanks for looking into this.

**Comment by einervonvielen** [comment]
Ah, thanks, the background color in $fancybox_bgcolour was set to #FFF instead of #FFFFFF
I will do a pull request soon. Obiously my browser does not like it.

There are other #FFF values that might cause problems too. I will fix them as well with another pull request because it might give problems and we can roll back easily.

There is still a problem left:
- The "Close" button of the calendar event popup vanishes if the browser window is resized. It is not inside the colorbox-div. Hmm.... no idea yet how to fix this one

**Comment by einervonvielen** [comment]
No, I won't fix the other #fff and #ccc and #777 and so on. I'm not quite sure what the orignal designer had in mind.

**Comment by einervonvielen** [comment]
Befor fix

![bildschirmfoto vom 2015-01-16 23 30 46](https://cloud.githubusercontent.com/assets/7354052/5791017/11b3f776-9eb6-11e4-87a4-d9a457fc78d5.png)

**Comment by einervonvielen** [comment]
After fix

![bildschirmfoto vom 2015-01-18 01 57 49](https://cloud.githubusercontent.com/assets/7354052/5791020/213037fa-9eb6-11e4-8b46-d1480226f7ae.png)

**Comment by pafcu** [comment]
Three-digit hex-codes should definitely work unless you are using some weird browser. From the CSS standard:
The three-digit RGB notation (#rgb) is converted into six-digit form (#rrggbb) by replicating digits, not by adding zeros. For example, #fb0 expands to #ffbb00.
