### ISSUE TITLE
In input groups button icons are not visible

### ISSUE THREAD

**Issue by cvogeley** [friendica/red#849]
The button icons are not visible in saved searches, people find and channel find input-groups.

**Comment by pafcu** [comment]
I can't seem to reproduce. What do you see instead? Are the buttons visible but empty? Could you take a screenshot to illustrate the problem?

**Comment by cvogeley** [comment]
Oh, sorry. I thought this was visible everywhere. I checked Safari, IE, Android,Chrome and Firefox.
I tried to fix it, but haven't been able so far.

That is what it looks like
![saved_searches](https://cloud.githubusercontent.com/assets/1605966/5736164/c94aa060-9bd2-11e4-8950-2093665e6525.PNG)
![find-channels](https://cloud.githubusercontent.com/assets/1605966/5736178/ffb00168-9bd2-11e4-8df4-98248061ff5b.PNG)

**Comment by friendica** [comment]
Not seeing those results here either. Any theme customisations?

**Comment by pafcu** [comment]
Works for me at least. I also looked at https://christian-vogeley.de which I assume is your hub, and it seems fine. Have you tried clearing your browser cache?

**Comment by cvogeley** [comment]
There shouldn't be any theme modifications in the code. But I have set application font sizes in the display settings to 90%. I just saw that if I remove this they become visible.

**Comment by pafcu** [comment]
So it seems it's a problem with OS X then? Would probably make sense to try to make a minimal HTML example where the problem is visible, to determine if it's a general problem, or some problem that appears only in combination with Red CSS.

**Comment by cvogeley** [comment]
No, I mean display settings in RedMatrix (settings/display) -->font settings for the entire application. This setting also affects the icons in input groups. I may have a further look at this, but I am still at work.

**Comment by pafcu** [comment]
Ah, OK, sorry for misunderstanding. Seems like the problem is line 2228 in view/theme/redbasic/css/style.css. Removing that rule fixes the problem (although it's not the correct solution), since it results in some other graphical issues.

**Comment by cvogeley** [comment]
By the way: are the buttons and text fields correctly aligned on your side? It looks like that for me on IE, I can check other browsers at home:
![saved_searches](https://cloud.githubusercontent.com/assets/1605966/5744135/455de4aa-9c1e-11e4-958a-276c63526fe2.PNG)
![find_channels](https://cloud.githubusercontent.com/assets/1605966/5744134/455dc39e-9c1e-11e4-9deb-8edb59b090ec.PNG)

**Comment by pafcu** [comment]
No such problems here, probably related to the font-size thing.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#172
