### ISSUE TITLE
Add some padding by default to tables generated with bbcode

### ISSUE THREAD

**Issue by pafcu** [friendica/red#861]
Currently table cells generated with bbcode don't have any padding, causing text in adjecant columns to run into each other sometimes.

To solve the problem:
1) In text/bbcode.php add a class, e.g. "bbtable" to generated tables (around line 616), all three cases.
2) Modify view/theme/redbasic/css/style.css to add some padding to cells in tables belonging to that class. Alternatively, the modification could be made to view/css/default.css if added padding should not depend on the theme.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#174
