### ISSUE TITLE
affinity slider needs to redraw the position indicators on window size change

### ISSUE THREAD

**Issue by friendica** [friendica/red#867]
The affinity slider no longer tracks window size changes and these can leave the slider at a position providing a visual indication which is not in sync with its internal value.

**Comment by pafcu** [comment]
https://github.com/nitinhayaran/jRange/issues/11

**Comment by pafcu** [comment]
Pull request submitted upstream:
https://github.com/nitinhayaran/jRange/pull/12

**Comment by pafcu** [comment]
Fixed upstream. I'll update the copy included in this repo soon.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#298
