### ISSUE TITLE
https://redmatrix.me has SSL issues in Chrome for OSX

### ISSUE THREAD

**Issue by webbj74** [friendica/red#871]
Site seems to work fine in Safari 8.0.3, Firefox 35.0, curl 7.37.1, Chrome 39.0.2171.50 for iOS

Chrome 39.0.2171.71 or 39.0.2171.99 (64-bit, OSX) give me a sad:

![ssl-redmatrix](https://cloud.githubusercontent.com/assets/50980/5809677/5fe7475a-a009-11e4-9921-6e1f0a68be61.png)

I ran a Qualys report on it and don't see anything too abnormal:
https://www.ssllabs.com/ssltest/analyze.html?d=redmatrix.me

Anyone else experiencing this?

**Comment by friendica** [comment]
No problems with Chrome 39.0.2171.99 m on Windows, so perhaps an OSX thing.

**Comment by webbj74** [comment]
I'm going to close this as a Chrome bug. Site works fine over https with the latest Canary version (42.0.2281.0 canary (64-bit))

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#300
