### ISSUE TITLE
include/attach.php - add .opus, .webm, OpenDocument standard

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#874]
Request some additional content types with suggested file extensions, three extra under audio/video and the OpenDocument standard

// audio/video
'mp3' => 'audio/mpeg',
'wav' => 'audio/wav',
'qt' => 'video/quicktime',
'mov' => 'video/quicktime',
'ogg' => 'application/ogg',
// New browsers support these directly:
'opus' => 'audio/ogg',
'webm' => 'audio/webm',
'webm' => 'video/webm',

// OpenDocument standard
'odt' => 'application/vnd.oasis.opendocument.text',
'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
'odp' => 'application/vnd.oasis.opendocument.presentation',
'odg' => 'application/vnd.oasis.opendocument.graphics',
'odc' => 'application/vnd.oasis.opendocument.chart',
'odf' => 'application/vnd.oasis.opendocument.formula',
'odi' => 'application/vnd.oasis.opendocument.image',
'odm' => 'application/vnd.oasis.opendocument.text-master',
'odb' => 'application/vnd.oasis.opendocument.base',
'odb' => 'application/vnd.oasis.opendocument.database',
'ott' => 'application/vnd.oasis.opendocument.text-template'
'ots' => 'application/vnd.oasis.opendocument.spreadsheet-template',
'otp' => 'application/vnd.oasis.opendocument.presentation-template',
'otg' => 'application/vnd.oasis.opendocument.graphics-template',
'otc' => 'application/vnd.oasis.opendocument.chart-template',
'otf' => application/vnd.oasis.opendocument.formula-template',
'oti' => 'application/vnd.oasis.opendocument.image-template'
'oth' => 'application/vnd.oasis.opendocument.text-web'

**Comment by pafcu** [comment]
Might also be worth taking a look at https://github.com/jshttp/mime-db. It includes all mime types from IANA and Apache.

**Comment by HaakonME** [comment]
Perhaps we should promote formats that do not require external dependencies, i.e. you should just need an up-to-date browser. WebODF, PDF.js, readium.js covers OpenDocument Format, PDF and EPUB, Opus covers sound and WebM covers video?

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#175
