### ISSUE TITLE
Delete Connection

### ISSUE THREAD

**Issue by ghost** [friendica/red#88]
After deleting one Connection in my Red Logfile:

dba_mysqli: ERROR: delete from mail where ( from_xchan = 'dzss3OhnoZR6Tj--52tEMVwcFc4jNLIEoOvWUkeUm9mgUDQpjjPKSJNtU7OIfDyLcRaL1JH1LN2vyEcRfIKNnA' or to_xchan = 'dzss3OhnoZR6Tj--52tEMVwcFc4jNLIEoOvWUkeUm9mgUDQpjjPKSJNtU7OIfDyLcRaL1JH1LN2vyEcRfIKNnA' ) and uid = 1 
Unknown column 'uid' in 'where clause'

?

PS: Apache-Log = OK
MySQL-Log = OK

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#33
