### ISSUE TITLE
Connecting to a channel via URL doesn't work

### ISSUE THREAD

**Issue by zzottel** [friendica/red#883]
A member I helped getting used to Red tried to connect to a channel by entering https://hub/channel/channelname in the box on the connection page and got "Protocol deactivated" (or similar, translated back from German).

I always thought that would work, too, and it should, to make things easy for new members. If that used to work, it seems to have been broken by the introduction of RSS feeds.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#179
