### ISSUE TITLE
No email send after an account registration is approved

### ISSUE THREAD

**Issue by jeroenpraat** [friendica/red#884]
When a registration needs approval a mail is send to the admin. After the admin has approved the registration you expect that the person who registered gets an email with the information that his/her account is approved. It's not. So this person can only know by visiting the RedMatrix hub that the account registration is approved. The person who asked for approval also doesn't receive a verification mail.

When this bug is fixed, keep in mind it's maybe a good idea to combine the verification mail and the mail that's saying the account registration is approved.

**Comment by friendica** [comment]
Works for me. Did you check the spam folder? Also site approval by the admin bypasses the email verification step. If the site admin approves you, you're in.  

An account has been created at Red Matrix for this email address. 
The login details are as follows:

Site Location:	https://***********
Login:   ****@************
Password: (the password which was provided during registration)

If this account was created without your knowledge and is not desired, you may 
visit this site and reset the password. This will allow you to remove the 
account from the links on the Settings page, and we 
apologise for any inconvenience. 

Thank you and welcome to Red Matrix.

Sincerely,
	Red Matrix Administrator

**Comment by jeroenpraat** [comment]
Nothing in the spamfolder. That would be strange, because I used an email alias for registering.  In other words, admin mail and member registration mail go to the same spamfilter. And I received the admin mail. 

Later today I will test it again, but keeping an eye on the server mail log.

**Comment by jeroenpraat** [comment]
One other thing: email verification mails (I've now fully opened registration) are received. So that works.

**Comment by jeroenpraat** [comment]
Found in the php error log php.out (I enabled again):

```
[01-Feb-2015 23:45:14 Europe/Amsterdam] PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "view/nl/register_open_eml.tpl"  on line 14 "Wanneer dit account wel door jou is aangemaakt: Dank je en welkom op de {{sitename}}." unknown tag "sitename" <--
  thrown in /var/www/redmatrix/library/Smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 14
```

**Comment by jeroenpraat** [comment]
Ah I see it, I forgot the $ in the translation. My fault. Mea Culpa.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#302
