### ISSUE TITLE
Diaspora members are not automatically approved

### ISSUE THREAD

**Issue by jeroenpraat** [friendica/red#885]
When a Diaspora member wants to connect to a channel and 'standard permissions for connections' is enabled they still need approval by the channel owner. The opposite is true for RedMatrix channels, they are automatically approved as expected.

**Comment by friendica** [comment]
Settings -> Connection Default Permissions

"apply these permissions automatically". (checkbox or on/off switch)

Is this enabled?

**Comment by friendica** [comment]
Note that page is only visible with certain permission role settings. What is the permissions role for the channel in question?

**Comment by friendica** [comment]
should be fixed

**Comment by jeroenpraat** [comment]
Thanks.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#303
