### ISSUE TITLE
Trying to make a post with a url containing "/#" makes a mess of the message

### ISSUE THREAD

**Issue by dwatney** [friendica/red#896]
It seems that having a /# followed sometime later by another / inside a URL makes things unhappy. The post preview as well as the resulting post, if you share it, are screwed up.

For example:
http://index.rsf.org/#!/index-details

Without the following slash, you get funky hashtags, but the most of the message doesn't disappear, as happens with the slash.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#181
