### ISSUE TITLE
Folders are not deletable if vowel mutations are in the name

### ISSUE THREAD

**Issue by Steffov** [friendica/red#903]
I notices that it's not possible to delete a folder, which is created under files, when they contains vowel mutations like ü,ä or ö. The vowel mutations are not displayed too. I was able to delete the folder on the site, after changing the ü to "ue" directly in the database.

**Comment by dawnbreak** [comment]
Could not reproduce this behaviour. Did you create this folder with mutated vowels in the browser or did you use a WebDAV client? Can you open such folder? You have other problems with ä,ö,ü in your hub, or only with folder in files?

**Comment by Steffov** [comment]
> Did you create this folder with mutated vowels in the browser or did you use a WebDAV client?
Yes, I create the folder in the browser. Today I tried this again. The result was the same. 

Here are the steps to reproduce:
1. Select Files (cloud)
2. Create new folder
3. Name the folder: Übersicht

Effects:
1. Try to open this new Folder
2. It will apear a xml error like this:
<d:error><s:exception>Sabre\DAV\Exception\NotFound</s:exception><s:message>The file with name: bersicht could not be found.</s:message><s:sabredav-version>1.8.10</s:sabredav-version></d:error>
3. Folder isn't deletable. In additional the folder name isn't correct. 
It's "bersicht". The correct spelling would be "Übersicht".

By now I couldn't find any other issues like that in my hub.

**Comment by friendica** [comment]
Able to duplicate exactly as described. Did find an issue creating directories in general which has now been fixed. This remains elusive. Trace statements show that we do hand the correct name to the Sabre library. It comes back mangled. It also seems to be dependent on the position of the accented character in the string. Creating blÜbersicht (probably not a real word, but I was testing this hypothesis) worked fine and was selectable. Übersicht was chopped at the first char. Trace statements inside the Sabre code haven't yet provided a clue where it is getting mangled.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#183
