### ISSUE TITLE
Channels and account can't be deleted anymore by member

### ISSUE THREAD

**Issue by jeroenpraat** [friendica/red#919]
When going to 'removeme' or 'removeaccount' the channel and account can't be removed. After filling in the password and pressing the red button, nothing is happening.

**Comment by git-marijus** [comment]
can you confirm the proposed fix?

**Comment by jeroenpraat** [comment]
Yes works. Thanks!!!

**Comment by git-marijus** [comment]
works for both?

**Comment by jeroenpraat** [comment]
Yes, both tested (created a test account).

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#308
