### ISSUE TITLE
Global settings forms for plugins and themes in admin area not shown

### ISSUE THREAD

**Issue by cvogeley** [friendica/red#93]
for example in the ported impressum addon https://github.com/cvogeley/red-addons/tree/master/impressum the settings form is not shown on the admin page under 
admin/plugins/impressum. I would expect the content created by the function  impressum_plugin_admin_post

I already tried to check if replacing argv(2) back with $a->argv[2] in the following bit would bring it back, but it doesn't.
	case 'plugins':
				if (argc() > 2 && 
					is_file("addon/" . argv(2) . "/" . argv(2) . ".php")){
						@include_once("addon/" . argv(2) . "/" . argv(2) . ".php");
						if(function_exists(argv(2).'_plugin_admin_post')) {
							$func = argv(2) . '_plugin_admin_post';
							$func($a);
						}
				}
				goaway($a->get_baseurl(true) . '/admin/plugins/' . argv(2) );
				return; // NOTREACHED
				break;

It seems like the same issue occurs for themes that use global settings.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#108
