### ISSUE TITLE
SQL error in sharedwithme.php

### ISSUE THREAD

**Issue by tokudan** [friendica/red#939]
Another SQL error (not sure when it appeared first):
Mar 24 21:50:01 ashe postgres[5058]: [3-1] 2015-03-24 21:50:01 CET [5058-1] redmatrix@redmatrix ERROR:  column "item.object" must appear in the GROUP BY clause or be used in an aggregate function at character 13
Mar 24 21:50:01 ashe postgres[5058]: [3-2] 2015-03-24 21:50:01 CET [5058-2] redmatrix@redmatrix STATEMENT:  SELECT mid, object FROM item WHERE verb = 'http://activitystrea.ms/schema/1.0/update' AND obj_type = 'http://purl.org/zot/activity/file' GROUP BY mid;

Seems to originate from include/sharedwithme.php:6.

**Comment by git-marijus** [comment]
hopefully fixed in 4900510
please confirm

**Comment by tokudan** [comment]
I haven't seen this error since the update, so I guess it's fixed.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#4
