### ISSUE TITLE
Page link title on web pages broken - cannot access page after saving

### ISSUE THREAD

**Issue by HaakonME** [friendica/red#942]
I am moving these articles - http://far.no/index.php?title=Kategori:Eventyr - to Parlementum as webpages. I access each article, then select and copy the title into the webpage form, both in the Title field and the Page link title field. The folktale is then copied into the content field, and the new page is submitted successfully.

The Page link title seems to be converted if it contains spaces and other characters.

However, when trying to access the page by clicking the generated page link title, this fails, and the page cannot be found. It is possible to manually change the page link title to something without special characters, then it works. As I have 144 articles, this is a bother, is it possible to fix it in the code?

**Comment by HaakonME** [comment]
For now, I am fixing this manually, but please consider fixing this to make large scale import easier.

Space is replaced by +, but this does not work, so I have switched + to _, i.e. underscore.
ø is replaced by %c3%b8 , which does not work, which I then manually have switched to simply o.
å is replaced by %c3%a5 , which does not work, which I then manually have switched to simply a.
æ I have switched to simply a.
Titles with commas and apostrophies have been replaced, but these do not work, and so I have manually deleted them.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#1

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#187
